### PR TITLE
`_handling` was treated incorrectly as early-return

### LINKED ISSUE #304: `nesting-depth` isn't triggered due to `_handling` (with `_return`) if `count-early-return-as-nesting-depth` is set to `false`
Given this snippet:

```
_method object.test
	_handling some_error _with _proc@mute() _return _endproc

	_local ok? << a = b
	_local success? << _true
	_try _with cond
		_if ok?.not
		_then
			success? _and<< _self.check_something()
		_else
			_self.do_something()

			_local c << _self.get_list()
			_local d << c.select(predicate.eq(:yourself, e))
			_if d.empty?
			_then _self.do_something_else()
			_endif

			success? _and<< _self.check_something_else()
			success? _and<< _self.check_one_more_thing()

			_if success?
			_then success? _and<< _self.do_one_more_thing()
			_endif
		_endif
	_when error
		success? << _false

		_dynamic !output!
		cond.report_on(!output!)
	_endtry

	>> success?
_endmethod
$
```

`nesting-depth` isn't triggered, due to `_handling some_error _proc@mute() _return _endproc` at the beginning.
I have set `count-early-return-as-nesting-depth` set to `false`. When setting it to `true` (default), it is always triggered, but I don't want to count early-return as nesting depth.

### PR DESCRIPTION
**Pull request by sebastiaanspeck**
Fixes #304

### CODE REVIEW

File: magik-checks/src/test/java/nl/ramsolutions/sw/magik/checks/checks/NestingDepthCheckTest.java [hunk 1]
```diff
@@ -154,4 +154,37 @@ void testValidWithEarlyReturnsNotAddingToNestingDepth(final String code) {
...
+              _if c
+              _then
+                write("Too deep!")
+              _endif
+            _endloop
+          _endif
+        _endmethod
+        """,
+      })
+  void testHandlingIsNotCountedAsValidEarlyReturn(final String code) {
```
Comment (StevenLooman) [inline magik-checks/src/test/java/nl/ramsolutions/sw/magik/checks/checks/NestingDepthCheckTest.java]: Please make this separate tests.

Comment (StevenLooman) [reply magik-checks/src/test/java/nl/ramsolutions/sw/magik/checks/checks/NestingDepthCheckTest.java]: Also, the `ValueSource` only provides one value. The code itself could be a regular variable/constant.

**Comment by StevenLooman** [comment]
Thanks!
